---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: centralmodel
  namespace: default
  labels:
    k8s-app: centralmodel
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: centralmodel
  template:
    metadata:
      name: centralmodel
      labels:
        k8s-app: centralmodel
    spec:
      containers:
        - name: centralmodel
          image: docker.io/bruced2iq/centralmodel:v7.9.1.2
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---  
kind: Service
apiVersion: v1
metadata:
  name: centralmodel
  namespace: default
  labels:
    k8s-app: centralmodel
spec:
  ports:
    - name: tcp-80-80-f7n7x
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    k8s-app: centralmodel
  type: LoadBalancer
